### ISSUE TITLE
PDF encode error

### ISSUE THREAD

**Issue by loseblue** [freedmand/semantra#10]
windows 10 system

```
❯ semantra.exe 38411-f00-NG-layer-1.pdf
38411-f00-NG-layer-1.pdf:   0%|                                                                                                                                                                                      | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\loseblue\.local\bin\semantra.exe\__main__.py", line 7, in <module>
  File "C:\Users\loseblue\.local\pipx\venvs\semantra\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\loseblue\.local\pipx\venvs\semantra\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\loseblue\.local\pipx\venvs\semantra\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\loseblue\.local\pipx\venvs\semantra\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\loseblue\.local\pipx\venvs\semantra\lib\site-packages\semantra\semantra.py", line 594, in main
    documents[fn] = process(
  File "C:\Users\loseblue\.local\pipx\venvs\semantra\lib\site-packages\semantra\semantra.py", line 146, in process
    content = get_text_content(md5, filename, semantra_dir, force, silent)
  File "C:\Users\loseblue\.local\pipx\venvs\semantra\lib\site-packages\semantra\semantra.py", line 45, in get_text_content
    return get_pdf_content(md5, filename, semantra_dir, force, silent)
  File "C:\Users\loseblue\.local\pipx\venvs\semantra\lib\site-packages\semantra\pdf.py", line 79, in get_pdf_content
    position += f.write(pagetext)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 422: illegal multibyte sequence
```

[38411-f00-NG-layer-1.pdf](https://github.com/freedmand/semantra/files/11328707/38411-f00-NG-layer-1.pdf)

**Comment by freedmand** [comment]
This should be fixed now.

Try running `pipx upgrade semantra` to bring in the latest changes. You can run `semantra --version` to verify you have them (0.1.3). If it doesn't work the first time, try again as that sometimes helps.

If this fix doesn't work, please re-open the issue. Thanks!
