### ISSUE TITLE
OpenAI key problem?

### ISSUE THREAD

**Issue by Foolevil** [freedmand/semantra#2]
Error:
Traceback (most recent call last):
  File "/Users/kidthecat/.local/bin/semantra", line 8, in <module>
    sys.exit(main())
  File "/Users/kidthecat/.local/pipx/venvs/semantra/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kidthecat/.local/pipx/venvs/semantra/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/kidthecat/.local/pipx/venvs/semantra/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kidthecat/.local/pipx/venvs/semantra/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kidthecat/.local/pipx/venvs/semantra/lib/python3.9/site-packages/semantra/semantra.py", line 581, in main
    model: BaseModel = model_config["get_model"]()
  File "/Users/kidthecat/.local/pipx/venvs/semantra/lib/python3.9/site-packages/semantra/models.py", line 320, in <lambda>
    "get_model": lambda: OpenAIModel(
  File "/Users/kidthecat/.local/pipx/venvs/semantra/lib/python3.9/site-packages/semantra/models.py", line 116, in __init__
    raise Exception(
Exception: OpenAI API key not set. Please set the OPENAI_API_KEY environment variable or create a `.env` file with the key in the same directory.

I tried .env and exporting the key, but something wrong. I got other OPenAI keys working with Auto-GPT, so the keys do work.

**Comment by Foolevil** [comment]
oh yes... didn't think of that. Woking ok now, thanks!
