### ISSUE TITLE
ValueError: Loading openbmb/cpm-bee-10b requires you to execute the tokenizer file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

### ISSUE THREAD

**Issue by geigerX** [freedmand/semantra#56]
Error occurred when executing command "semantra --transformer-model openbmb/cpm-bee-10b <filenames> xxx.txt" to use HuggingFace model _openbmb/cpm-bee-10b_. Detailed message shown below:
Traceback (most recent call last):
  File "/Users/macbookuser/.local/bin/semantra", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/macbookuser/.local/pipx/venvs/semantra/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookuser/.local/pipx/venvs/semantra/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/macbookuser/.local/pipx/venvs/semantra/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookuser/.local/pipx/venvs/semantra/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookuser/.local/pipx/venvs/semantra/lib/python3.11/site-packages/semantra/semantra.py", line 583, in main
    model = TransformerModel(
            ^^^^^^^^^^^^^^^^^
  File "/Users/macbookuser/.local/pipx/venvs/semantra/lib/python3.11/site-packages/semantra/models.py", line 166, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookuser/.local/pipx/venvs/semantra/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 669, in from_pretrained
    raise ValueError(
ValueError: Loading openbmb/cpm-bee-10b requires you to execute the tokenizer file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

Could anyone tell me how to fix this error? Thanks a lot!

**Comment by freedmand** [comment]
I'm not sure if that model is compatible with Semantra. It appears to be more of a translation model (sequence-to-sequence) instead of a representation model that is suitable for semantic similarity. See #53
