### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by rybla** [freedmand/semantra#72]
When running `semantra --version` after successfully installing, I get

```
semantra --version
Traceback (most recent call last):
  File "/home/henry/Documents/semantra/venv/bin/semantra", line 5, in <module>
    from semantra.semantra import main
  File "/home/henry/Documents/semantra/venv/lib/python3.12/site-packages/semantra/semantra.py", line 9, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by rybla** [comment]
_Solution._ Install Python module `setuptools`. This should probably be done already by installation though.

**Comment by freedmand** [comment]
0.1.9 adds a dependency to `setuptools` which should resolve this issue for future users
