### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by mdinata** [freedmand/semantra#79]
Found this error when running semantra demo file.
Semantra installation went smooth. Here is the environment
```
(semantra) C:\Users\andi\Downloads>pip list
Package      Version
------------ -------
argcomplete  3.4.0
click        8.1.7
colorama     0.4.6
numpy        1.26.0
packaging    24.1
pip          24.0
pipx         1.6.0
platformdirs 4.2.2
setuptools   65.5.0
userpath     1.9.2

(semantra) C:\Users\andi\Downloads>python -V
Python 3.11.9
```
Error found, although numpy is installed. Thanks in advance to suggest the fix. 
Regards

```(semantra) C:\Users\andi\Downloads>semantra hamlet.pdf

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\andi\.local\bin\semantra.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\semantra\semantra.py", line 606, in main
    model: BaseModel = model_config["get_model"]()
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\semantra\models.py", line 334, in <lambda>
    "get_model": lambda: TransformerModel(model_name=mpnet_model_name),
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\semantra\models.py", line 167, in __init__
    self.model = AutoModel.from_pretrained(model_name)
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\transformers\modeling_utils.py", line 3556, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\transformers\modeling_utils.py", line 515, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\safetensors\torch.py", line 313, in load_file
    result[k] = f.get_tensor(k)
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\torch\storage.py", line 321, in __getitem__
    return super().__getitem__(*args, **kwargs)
C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\torch\storage.py:321: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  return super().__getitem__(*args, **kwargs)
hamlet.pdf:   0%|                                                                                | 0/1 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\andi\.local\bin\semantra.exe\__main__.py", line 7, in <module>
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\semantra\semantra.py", line 619, in main
    documents[fn] = process(
                    ^^^^^^^^
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\semantra\semantra.py", line 304, in process
    flush_pool()
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\semantra\semantra.py", line 276, in flush_pool
    embeddings[
  File "C:\Users\andi\pipx\venvs\semantra\Lib\site-packages\torch\_tensor.py", line 1089, in __array__
    return self.numpy().astype(dtype, copy=False)
           ^^^^^^^^^^^^
RuntimeError: Numpy is not available```

**Comment by yulongwanxue** [comment]
me too

**Comment by justinrporter** [comment]
I suspect this is related to the recent numpy 2.0.0 release. Either semantra or a dependency needs to limit to numpy < 2.0. 

If you manually install eg `numpy==1.26.4` it resolves this error.

**Comment by mdinata** [comment]
> I suspect this is related to the recent numpy 2.0.0 release. Either semantra or a dependency needs to limit to numpy < 2.0.
> 
> If you manually install eg `numpy==1.26.4` it resolves this error.

Thanks for the advise. I had the same thought that numpy 2.0 might be cause to the problem. And thus the numpy version was downgraded to 1.26 (as you might see in my post, that installed numpy package is already at 1.26).

Anyway, that error reproduced in Miniconda3 environment of other Windows 11 machine. However, no such error found (semantra runs perfectly at localhost:8080 when it is installed in Miniconda3 environment on PopOS (Ubuntu 22.04) which interestingly found no numpy package.

```(semantra) andi@pop-os:~/Documents/Journal/genz$ pip list
Package      Version
------------ -------
argcomplete  3.4.0
click        8.1.7
packaging    24.1
pip          24.0
pipx         1.6.0
platformdirs 4.2.2
setuptools   69.5.1
tomli        2.0.1
userpath     1.9.2
wheel        0.43.0
(semantra) andi@pop-os:~/Documents/Journal/genz$ python
Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
>>> exit()

(semantra) andi@pop-os:~/Documents/Journal/genz$ semantra leslie2021.pdf --port 8081
leslie2021.pdf: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 192.12it/s]
 * Serving Flask app 'semantra.semantra'                                                     
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8081
Press CTRL+C to quit```

Anyway I consider this is closed.
